/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'maleTshirts' : IDL.Null,
  'femaleDresses' : IDL.Null,
  'maleShirts' : IDL.Null,
  'kidsApparel' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({
  'size' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'category' : Category,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const StaticStoreContent = IDL.Record({
  'aboutPageCopy' : IDL.Text,
  'heroText' : IDL.Text,
  'heroBanner' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getStoreContent' : IDL.Func([], [StaticStoreContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeStore' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isShouldBeAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(CartItem), IDL.Float64], [IDL.Nat], []),
  'removeAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateStoreContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'maleTshirts' : IDL.Null,
    'femaleDresses' : IDL.Null,
    'maleShirts' : IDL.Null,
    'kidsApparel' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'size' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'category' : Category,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const StaticStoreContent = IDL.Record({
    'aboutPageCopy' : IDL.Text,
    'heroText' : IDL.Text,
    'heroBanner' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreContent' : IDL.Func([], [StaticStoreContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeStore' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isShouldBeAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Vec(CartItem), IDL.Float64], [IDL.Nat], []),
    'removeAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateStoreContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };