/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export type Category = { 'maleTshirts' : null } |
  { 'femaleDresses' : null } |
  { 'maleShirts' : null } |
  { 'kidsApparel' : null };
export interface Order {
  'id' : bigint,
  'status' : string,
  'userId' : string,
  'totalAmount' : number,
  'timestamp' : bigint,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'category' : Category,
  'image' : string,
  'price' : number,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, Category, string, number, Array<string>, bigint, string],
    bigint
  >,
  'addToCart' : ActorMethod<[string, bigint, string, bigint], undefined>,
  'clearCart' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getOrders' : ActorMethod<[string], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'initializeStore' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<[string, Array<CartItem>, number], bigint>,
  'removeFromCart' : ActorMethod<[string, bigint, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, Category, string, number, Array<string>, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];