/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'maleTshirts' : IDL.Null,
  'femaleDresses' : IDL.Null,
  'maleShirts' : IDL.Null,
  'kidsApparel' : IDL.Null,
});
export const CartItem = IDL.Record({
  'size' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(CartItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'category' : Category,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'initializeStore' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(CartItem), IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'maleTshirts' : IDL.Null,
    'femaleDresses' : IDL.Null,
    'maleShirts' : IDL.Null,
    'kidsApparel' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'size' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(CartItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'category' : Category,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initializeStore' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(CartItem), IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };